name: Action
on:
  push:
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: registry.gitlab.steamos.cloud/steamrt/sniper/sdk
    steps:
      - name: Check for dockerenv file
        run: (ls /.dockerenv && echo Found dockerenv) || (echo No dockerenv)
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Build
        run: |
          cd Plugins/Linux/StandaloneFileBrowser
          make all
      - name: Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: libStandaloneFileBrowser.so
          path: Plugins/Linux/StandaloneFileBrowser/build/

